ALTER TABLE er_enterprise_profile ADD COLUMN sales_manager VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE er_enterprise_profile ADD COLUMN latest_collection_batch_no VARCHAR(40);
ALTER TABLE er_collection_run ADD COLUMN batch_no VARCHAR(40);
ALTER TABLE er_collection_run ADD COLUMN trigger_type VARCHAR(24) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE er_collection_run ADD COLUMN scope_description VARCHAR(500);
CREATE UNIQUE INDEX uq_er_collection_run_batch_no ON er_collection_run(batch_no);
CREATE INDEX idx_er_profile_sales_manager ON er_enterprise_profile(sales_manager);
CREATE INDEX idx_er_profile_batch_no ON er_enterprise_profile(latest_collection_batch_no);
CREATE TABLE er_collection_schedule (id INT PRIMARY KEY, enabled BOOLEAN NOT NULL DEFAULT FALSE, frequency VARCHAR(16) NOT NULL DEFAULT 'DAILY', run_time VARCHAR(5) NOT NULL DEFAULT '02:00', day_of_week INT, last_trigger_key VARCHAR(32), updated_by VARCHAR(100), updated_at TIMESTAMP NOT NULL);
INSERT INTO er_collection_schedule(id,enabled,frequency,run_time,updated_at) VALUES(1,FALSE,'DAILY','02:00',CURRENT_TIMESTAMP);
CREATE TABLE er_wecom_robot_config (id INT PRIMARY KEY, enabled BOOLEAN NOT NULL DEFAULT FALSE, webhook_ciphertext LONGTEXT, updated_by VARCHAR(100), updated_at TIMESTAMP NOT NULL);
INSERT INTO er_wecom_robot_config(id,enabled,updated_at) VALUES(1,FALSE,CURRENT_TIMESTAMP);
CREATE TABLE er_wecom_notification_log (id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id BIGINT NOT NULL, batch_no VARCHAR(40) NOT NULL, status VARCHAR(24) NOT NULL, retry_count INT NOT NULL DEFAULT 0, message_text LONGTEXT NOT NULL, response_summary VARCHAR(1000), sent_at TIMESTAMP, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_wecom_log_run FOREIGN KEY(run_id) REFERENCES er_collection_run(id));
