package com.tehang.enterpriserisk.service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;
import javax.crypto.Mac;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

@Service
public class AuthService {
  private final JdbcTemplate db; private final byte[] secret; private final String bootstrapAdminPassword; private final boolean requireBootstrapAdminPassword; private final SecureRandom random = new SecureRandom();
  public AuthService(JdbcTemplate db,@Value("${enterprise-risk.jwt-secret}") String secret,@Value("${enterprise-risk.bootstrap-admin-password:}") String bootstrapAdminPassword,@Value("${enterprise-risk.require-bootstrap-admin-password:false}") boolean requireBootstrapAdminPassword){this.db=db;this.secret=secret.getBytes(StandardCharsets.UTF_8);this.bootstrapAdminPassword=bootstrapAdminPassword;this.requireBootstrapAdminPassword=requireBootstrapAdminPassword;}
  @jakarta.annotation.PostConstruct public void bootstrap(){if(db.queryForObject("select count(*) from er_account",Integer.class)==0){String password=bootstrapAdminPassword==null||bootstrapAdminPassword.isBlank()?"admin":bootstrapAdminPassword;if(requireBootstrapAdminPassword&&password.length()<12)throw new IllegalStateException("首次初始化必须设置至少12位 ENTERPRISE_RISK_BOOTSTRAP_ADMIN_PASSWORD");Instant n=Instant.now();db.update("insert into er_account(login_account,password_hash,employee_name,role,enabled,must_change_password,created_at,updated_at) values(?,?,?,?,true,true,?,?)","admin",hash(password),"系统管理员","ADMIN",n,n);}}
  public Map<String,Object> login(String account,String password){Map<String,Object> u=db.queryForMap("select a.id,a.login_account loginAccount,a.employee_name employeeName,a.role,a.enabled,a.must_change_password mustChangePassword,a.password_hash passwordHash,r.role_name roleName from er_account a left join er_role r on r.role_code=a.role where a.login_account=?",account);if(!Boolean.TRUE.equals(u.get("enabled"))||!MessageDigest.isEqual(hash(password).getBytes(),String.valueOf(u.get("passwordHash")).getBytes()))throw new IllegalArgumentException("账号或密码错误");String token=token(account,String.valueOf(u.get("role")));return Map.of("token",token,"account",u.get("loginAccount"),"employeeName",u.get("employeeName"),"role",u.get("role"),"roleName",u.get("roleName")==null?u.get("role"):u.get("roleName"),"permissions",permissions(String.valueOf(u.get("role"))),"mustChangePassword",u.get("mustChangePassword"));}
  public Map<String,String> current(String token){String[] p=parse(token);return Map.of("account",p[0],"role",p[1]);}
  public void changePassword(String account,String password){if(password==null||password.length()<6)throw new IllegalArgumentException("密码至少6位");db.update("update er_account set password_hash=?,must_change_password=false,updated_at=? where login_account=?",hash(password),Instant.now(),account);}
  public List<Map<String,Object>> accounts(){return db.queryForList("select a.id,a.login_account,a.employee_name,a.phone,a.role,r.role_name,a.enabled,a.must_change_password,a.created_at from er_account a left join er_role r on r.role_code=a.role order by a.id").stream().map(x->{Map<String,Object> y=new LinkedHashMap<>();y.put("id",val(x,"ID","id"));y.put("loginAccount",val(x,"LOGIN_ACCOUNT","login_account","loginaccount"));y.put("employeeName",val(x,"EMPLOYEE_NAME","employee_name","employeename"));y.put("phone",val(x,"PHONE","phone"));y.put("role",val(x,"ROLE","role"));y.put("roleName",val(x,"ROLE_NAME","role_name","rolename"));y.put("enabled",val(x,"ENABLED","enabled"));y.put("mustChangePassword",val(x,"MUST_CHANGE_PASSWORD","must_change_password","mustchangepassword"));y.put("createdAt",val(x,"CREATED_AT","created_at","createdat"));return y;}).toList();}
  public List<Map<String,Object>> roles(){return db.queryForList("select r.role_code,r.role_name,r.enabled,(select count(*) from er_account a where a.role=r.role_code) account_count from er_role r order by r.id").stream().map(x->{Map<String,Object> y=new LinkedHashMap<>();y.put("roleCode",val(x,"ROLE_CODE","role_code","roleCode","rolecode"));y.put("roleName",val(x,"ROLE_NAME","role_name","roleName","rolename"));y.put("enabled",val(x,"ENABLED","enabled"));y.put("accountCount",val(x,"ACCOUNT_COUNT","account_count","accountCount","accountcount"));return y;}).toList();}
  public List<Map<String,Object>> enabledRoles(){return roles().stream().filter(x->Boolean.TRUE.equals(x.get("enabled"))).map(x->{Map<String,Object> y=new LinkedHashMap<>();y.put("roleCode",x.get("roleCode"));y.put("roleName",x.get("roleName"));return y;}).toList();}
  public List<Map<String,Object>> permissionDefinitions(){return List.of(
    Map.of("group","菜单权限","items",List.of(Map.of("code","MENU_RISK","name","企业风控"),Map.of("code","MENU_MODEL","name","风险等级"),Map.of("code","MENU_KEY","name","风控密钥"),Map.of("code","MENU_ROBOT","name","群机器人"),Map.of("code","MENU_ACCOUNTS","name","系统账号"),Map.of("code","MENU_ROLES","name","角色管理"))),
    Map.of("group","操作权限","items",List.of(Map.of("code","RISK_VIEW","name","查看企业风控"),Map.of("code","RISK_WRITE","name","维护/采集企业"),Map.of("code","MODEL_VIEW","name","查看风险等级"),Map.of("code","MODEL_MANAGE","name","配置风险等级"),Map.of("code","KEY_VIEW","name","查看风控密钥"),Map.of("code","KEY_MANAGE","name","管理风控密钥"),Map.of("code","ROBOT_VIEW","name","查看群机器人"),Map.of("code","ROBOT_MANAGE","name","配置群机器人"),Map.of("code","ACCOUNT_MANAGE","name","管理系统账号"),Map.of("code","ROLE_MANAGE","name","管理角色")))
  );}
  public List<String> permissions(String role){return db.queryForList("select permission_code from er_role_permission rp join er_role r on r.id=rp.role_id where r.role_code=? and r.enabled=true",String.class,role);}
  public Map<String,Object> role(String code){Map<String,Object> x=db.queryForMap("select role_code roleCode,role_name roleName,enabled from er_role where role_code=?",code);x.put("permissions",permissions(code));return x;}
  public Map<String,Object> saveRole(String code,String name,Boolean enabled,List<String> ps){Instant n=Instant.now(); if(code==null){throw new IllegalArgumentException("角色标识不能为空");} if(db.queryForObject("select count(*) from er_role where role_code=?",Integer.class,code)==0)db.update("insert into er_role(role_code,role_name,enabled,created_at,updated_at) values(?,?,?,?,?)",code,name.trim(),enabled==null||enabled,n,n);else db.update("update er_role set role_name=?,enabled=?,updated_at=? where role_code=?",name.trim(),enabled==null||enabled,n,code);db.update("delete from er_role_permission where role_id=(select id from er_role where role_code=?)",code);if(ps!=null)for(String p:ps)db.update("insert into er_role_permission(role_id,permission_code) select id,? from er_role where role_code=?",p,code);return role(code);}
  public void roleStatus(String code,boolean enabled){if(!enabled&&db.queryForObject("select count(*) from er_account where role=?",Integer.class,code)>0)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.CONFLICT,"该角色仍绑定账号，请先转移账号");db.update("update er_role set enabled=?,updated_at=? where role_code=?",enabled,Instant.now(),code);}
  public boolean hasPermission(String role,String permission){
    if (role==null) return false;
    Integer n=db.queryForObject("select count(*) from er_role_permission rp join er_role r on r.id=rp.role_id where r.role_code=? and r.enabled=true and (rp.permission_code='*' or rp.permission_code=?)",Integer.class,role,permission);
    return n!=null&&n>0;
  }
  public Map<String,Object> save(Long id,String account,String name,String phone,String role,String password){if(role==null||db.queryForObject("select count(*) from er_role where role_code=? and enabled=true",Integer.class,role)==0)throw new IllegalArgumentException("角色不存在或已停用");Long target=id;if(id==null){if(password==null||password.isBlank())password="123456";db.update("insert into er_account(login_account,password_hash,employee_name,phone,role,enabled,must_change_password,created_at,updated_at) values(?,?,?,?,?,true,false,?,?)",account,hash(password),name,phone,role,Instant.now(),Instant.now());target=db.queryForObject("select max(id) from er_account",Long.class);}else db.update("update er_account set employee_name=?,phone=?,role=?,updated_at=? where id=?",name,phone,role,Instant.now(),id);Map<String,Object> x=db.queryForMap("select id,login_account,employee_name,phone,role,enabled,must_change_password from er_account where id=?",target);Map<String,Object> y=new LinkedHashMap<>();y.put("id",val(x,"ID","id"));y.put("loginAccount",val(x,"LOGIN_ACCOUNT","login_account","loginaccount"));y.put("employeeName",val(x,"EMPLOYEE_NAME","employee_name","employeename"));y.put("phone",val(x,"PHONE","phone"));y.put("role",val(x,"ROLE","role"));y.put("enabled",val(x,"ENABLED","enabled"));y.put("mustChangePassword",val(x,"MUST_CHANGE_PASSWORD","must_change_password","mustchangepassword"));return y;}
  public void status(long id,boolean enabled){db.update("update er_account set enabled=?,updated_at=? where id=?",enabled,Instant.now(),id);}
  public void reset(long id){db.update("update er_account set password_hash=?,must_change_password=true,updated_at=? where id=?",hash("123456"),Instant.now(),id);}
  private String token(String account,String role){long exp=System.currentTimeMillis()/1000+604800;String h=b64("{\"alg\":\"HS256\",\"typ\":\"JWT\"}");String p=b64("{\"sub\":\""+account+"\",\"role\":\""+role+"\",\"exp\":"+exp+"}");return h+"."+p+"."+sig(h+"."+p);}
  private String[] parse(String token){try{String[] a=token.split("\\.");if(a.length!=3||!sig(a[0]+"."+a[1]).equals(a[2]))throw new Exception();String p=new String(Base64.getUrlDecoder().decode(a[1]),StandardCharsets.UTF_8);String sub=p.split("\\\"sub\\\":\\\"")[1].split("\\\"")[0];String role=p.split("\\\"role\\\":\\\"")[1].split("\\\"")[0];long exp=Long.parseLong(p.split("\\\"exp\\\":")[1].split("}")[0]);if(exp<System.currentTimeMillis()/1000)throw new Exception();return new String[]{sub,role};}catch(Exception e){throw new IllegalArgumentException("登录已过期");}}
  private String sig(String x){try{Mac m=Mac.getInstance("HmacSHA256");m.init(new javax.crypto.spec.SecretKeySpec(secret,"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(m.doFinal(x.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  private String b64(String x){return Base64.getUrlEncoder().withoutPadding().encodeToString(x.getBytes(StandardCharsets.UTF_8));}
  private String hash(String p){try{byte[] salt="enterprise-risk-salt".getBytes(StandardCharsets.UTF_8);var spec=new javax.crypto.spec.PBEKeySpec(p.toCharArray(),salt,120000,256);return Base64.getEncoder().encodeToString(javax.crypto.SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded());}catch(Exception e){throw new IllegalStateException(e);}}
  private Object val(Map<String,Object> m,String... keys){for(String k:keys)if(m.containsKey(k))return m.get(k);return null;}
}
