package com.tehang.enterpriserisk.service;

import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class BatchCollectionService {
  private static final int CAPABILITIES_PER_ENTERPRISE = RiskService.CAPS.size();
  private final JdbcTemplate db; private final RiskService risk; private final KeyService keys; private final WecomRobotService robot;
  public BatchCollectionService(JdbcTemplate d,RiskService r,KeyService k,WecomRobotService w){db=d;risk=r;keys=k;robot=w;}
  private String no(){String date=DateTimeFormatter.BASIC_ISO_DATE.format(LocalDate.now()),prefix="ER"+date;String latest=db.queryForObject("select max(batch_no) from er_collection_run where batch_no like ?",String.class,prefix+"%");int next=1;if(latest!=null&&latest.length()==prefix.length()+4)try{next=Integer.parseInt(latest.substring(prefix.length()))+1;}catch(NumberFormatException ignored){}if(next>9999)throw new IllegalStateException("当天采集批次号已用尽");return prefix+String.format("%04d",next);}
  public Map<String,Object> preview(){List<Long>ids=eligible();int remaining=keys.remainingToday();return Map.of("eligibleCount",ids.size(),"remainingQuota",remaining,"estimatedFullCapacity",remaining/CAPABILITIES_PER_ENTERPRISE,"scopeDescription","监测开启、首次采集或已达到风险周期、当前无进行中任务的企业");}
  private List<Long> eligible(){Instant now=Instant.now();List<Map<String,Object>>rows=db.queryForList("select id,risk_level \"riskLevel\",latest_success_at \"latestSuccessAt\",next_collection_at \"nextCollectionAt\",collection_status \"collectionStatus\" from er_enterprise_profile where deleted=false and monitoring_enabled=true and collection_status<>'COLLECTING' and not exists (select 1 from er_collection_attempt a where a.profile_id=er_enterprise_profile.id and a.status='COLLECTING')");return rows.stream().filter(r->isDue(r,now)).sorted(Comparator.<Map<String,Object>>comparingInt(r->priority(String.valueOf(r.get("riskLevel")))).reversed().thenComparing(r->dueAt(r,now))).map(r->((Number)r.get("id")).longValue()).toList();}
  private boolean isDue(Map<String,Object>r,Instant now){Instant next=instant(r.get("nextCollectionAt"));if(next!=null)return !next.isAfter(now);Instant success=instant(r.get("latestSuccessAt"));if(success==null)return true;return !success.plus(Duration.ofDays(cadenceDays(String.valueOf(r.get("riskLevel"))))).isAfter(now);}
  private Instant dueAt(Map<String,Object>r,Instant now){Instant next=instant(r.get("nextCollectionAt"));if(next!=null)return next;Instant success=instant(r.get("latestSuccessAt"));return success==null?Instant.MIN:success.plus(Duration.ofDays(cadenceDays(String.valueOf(r.get("riskLevel")))));}
  private int priority(String level){String base=level==null?"":level.split("\\*",2)[0];return switch(base){case "CRITICAL"->5;case "HIGH"->4;case "MEDIUM"->3;case "LOW"->2;default->1;};}
  private int cadenceDays(String level){return priority(level)>=3?7:15;}
  private Instant instant(Object value){if(value==null)return null;if(value instanceof Instant i)return i;if(value instanceof java.sql.Timestamp t)return t.toInstant();if(value instanceof java.util.Date d)return d.toInstant();try{return Instant.parse(String.valueOf(value));}catch(Exception e){return null;}}
  public Map<String,Object>executeManual(String actor){return start(eligible(),"MANUAL",actor,"统一周期规则下的到期企业");}
  public Map<String,Object>executeScheduled(){return start(eligible(),"SCHEDULED","SYSTEM","按风险等级周期到期企业，按日配额分片续跑");}
  private synchronized Map<String,Object>start(List<Long>ids,String type,String actor,String scope){if(db.queryForObject("select count(*) from er_collection_run where status='COLLECTING'",Integer.class)>0)throw new IllegalStateException("当前已有进行中采集批次");if(ids.isEmpty())throw new IllegalStateException("当前没有符合周期规则的待采集企业");int capacity=keys.remainingToday();if(capacity<=0)throw new IllegalStateException("当日天眼查Key配额已用完，等待次日自动续跑");int max=Math.max(1,capacity/CAPABILITIES_PER_ENTERPRISE);List<Long>slice=ids.subList(0,Math.min(max,ids.size()));Instant now=Instant.now();String batch=no();db.update("insert into er_collection_run(batch_no,trigger_type,status,total_count,created_by,scope_description,created_at) values(?,?, 'COLLECTING',?,?,?,?)",batch,type,slice.size(),actor,scope,now);long run=db.queryForObject("select id from er_collection_run where batch_no=?",Long.class,batch);db.update("update er_enterprise_profile set latest_collection_batch_no=?,updated_at=? where id in ("+placeholders(slice.size())+")",args(batch,now,slice));CompletableFuture.runAsync(()->process(run,batch,slice));return Map.of("runId",run,"batchNo",batch,"status","COLLECTING","total",slice.size(),"success",0,"partial",0,"failed",0);}
  private void process(long run,String batch,List<Long>ids){int success=0,partial=0,failed=0;boolean quotaPaused=false;for(Long id:ids){try{String status=String.valueOf(risk.scanQueued(id,run).get("status"));if("SUCCEEDED".equals(status))success++;else if("PARTIAL".equals(status))partial++;else if("PENDING_QUOTA".equals(status)){quotaPaused=true;break;}else failed++;}catch(Exception e){failed++;}}String status=quotaPaused?"PAUSED_QUOTA":failed==0&&partial==0?"SUCCEEDED":success+partial==0?"FAILED":"PARTIAL";db.update("update er_collection_run set status=?,success_count=?,partial_count=?,failure_count=?,completed_at=? where id=?",status,success,partial,failed,Instant.now(),run);try{robot.notifyRun(run,batch);}catch(Exception ignored){}}
  public Map<String,Object> progress(){List<Long>ids=eligible();int monitored=db.queryForObject("select count(*) from er_enterprise_profile where deleted=false and monitoring_enabled=true",Integer.class);int collecting=db.queryForObject("select count(*) from er_enterprise_profile where deleted=false and collection_status='COLLECTING'",Integer.class);int pending=db.queryForObject("select count(*) from er_enterprise_profile where deleted=false and collection_status='PENDING_QUOTA'",Integer.class);int remaining=keys.remainingToday();int perDay=Math.max(1,keys.dailyCapacity()/CAPABILITIES_PER_ENTERPRISE);return Map.of("monitoredCount",monitored,"dueCount",ids.size(),"pendingQuotaCount",pending,"collectingCount",collecting,"remainingQuota",remaining,"estimatedDays",ids.isEmpty()?0:(int)Math.ceil((double)ids.size()/perDay));}
  public Map<String,Object>run(long id){try{Map<String,Object>r=db.queryForMap("select id,batch_no,trigger_type,status,total_count,success_count,partial_count,failure_count,created_by,scope_description,created_at,completed_at from er_collection_run where id=?",id);Map<String,Object>o=new LinkedHashMap<>();o.put("id",r.get("id"));o.put("batchNo",r.get("batch_no"));o.put("triggerType",r.get("trigger_type"));o.put("status",r.get("status"));o.put("totalCount",r.get("total_count"));o.put("successCount",r.get("success_count"));o.put("partialCount",r.get("partial_count"));o.put("failureCount",r.get("failure_count"));o.put("createdBy",r.get("created_by"));o.put("scopeDescription",r.get("scope_description"));o.put("createdAt",r.get("created_at"));o.put("completedAt",r.get("completed_at"));Map<String,Object>riskCounts=db.queryForMap("select sum(case when risk_level like 'CRITICAL%' then 1 else 0 end) criticalCount,sum(case when risk_level like 'HIGH%' then 1 else 0 end) highCount,sum(case when risk_level like 'MEDIUM%' then 1 else 0 end) mediumCount,sum(case when risk_level like 'LOW%' then 1 else 0 end) lowCount from er_enterprise_profile where latest_collection_batch_no=? and deleted=false",r.get("batch_no"));riskCounts.forEach((k,v)->o.put(k,v==null?0:((Number)v).intValue()));return o;}catch(org.springframework.dao.EmptyResultDataAccessException e){throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"采集批次不存在");}}
  private String placeholders(int n){return String.join(",",Collections.nCopies(n,"?"));}private Object[]args(String batch,Instant now,List<Long>ids){List<Object>a=new ArrayList<>();a.add(batch);a.add(now);a.addAll(ids);return a.toArray();}
  public List<Map<String,Object>>runs(){return db.queryForList("select id,batch_no batchNo,trigger_type triggerType,status,total_count totalCount,success_count successCount,partial_count partialCount,failure_count failureCount,created_by createdBy,scope_description scopeDescription,created_at createdAt,completed_at completedAt from er_collection_run order by id desc");}
  public Map<String,Object>schedule(){Map<String,Object>r=db.queryForMap("select enabled,frequency,run_time,day_of_week,updated_by,updated_at,last_trigger_key from er_collection_schedule where id=1");Map<String,Object>x=new LinkedHashMap<>();x.put("enabled",r.get("enabled"));x.put("frequency",r.get("frequency"));x.put("runTime",r.get("run_time"));x.put("dayOfWeek",r.get("day_of_week"));x.put("updatedBy",r.get("updated_by"));x.put("updatedAt",r.get("updated_at"));x.put("lastTriggerKey",r.get("last_trigger_key"));return x;}
  public void saveSchedule(boolean enabled,String frequency,String runTime,Integer day,String actor){
    if(!Set.of("DAILY","WEEKLY").contains(frequency))throw new IllegalArgumentException("自动化采集频率必须为每日或每周");
    if("WEEKLY".equals(frequency)&&(day==null||day<1||day>7))throw new IllegalArgumentException("每周执行日必须为星期一至星期日");
    db.update("update er_collection_schedule set enabled=?,frequency=?,run_time='23:00',day_of_week=?,updated_by=?,updated_at=? where id=1",enabled,frequency,"WEEKLY".equals(frequency)?day:null,actor,Instant.now());
  }
  public static boolean scheduleDue(Map<String,Object>s,LocalDateTime n){
    if(!Boolean.TRUE.equals(s.get("enabled")))return false;
    if(n.getHour()!=23||n.getMinute()!=0)return false;
    String frequency=String.valueOf(s.get("frequency"));
    if("DAILY".equals(frequency))return true;
    if(!"WEEKLY".equals(frequency))return false;
    Object day=s.get("dayOfWeek");
    return day instanceof Number && ((Number)day).intValue()==n.getDayOfWeek().getValue();
  }
  @Scheduled(fixedDelay=60000)public void trigger(){try{Map<String,Object>s=schedule();LocalDateTime n=LocalDateTime.now();if(!scheduleDue(s,n))return;String frequency=String.valueOf(s.get("frequency"));String day="WEEKLY".equals(frequency)?String.valueOf(n.getDayOfWeek().getValue()):"-";String key=n.toLocalDate()+" 23:00 "+frequency+" "+day;if(!key.equals(s.get("lastTriggerKey"))){try{executeScheduled();}catch(Exception ignored){}db.update("update er_collection_schedule set last_trigger_key=? where id=1",key);}}catch(Exception ignored){}}
}
