CREATE TABLE er_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code VARCHAR(64) NOT NULL UNIQUE,
  role_name VARCHAR(100) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
CREATE TABLE er_role_permission (
  role_id BIGINT NOT NULL,
  permission_code VARCHAR(100) NOT NULL,
  PRIMARY KEY(role_id, permission_code),
  CONSTRAINT fk_role_permission_role FOREIGN KEY(role_id) REFERENCES er_role(id) ON DELETE CASCADE
);
INSERT INTO er_role(role_code,role_name,enabled,created_at,updated_at)
VALUES ('ADMIN','系统管理员',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
       ('OPERATIONS','运营人员',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
       ('VIEWER','只读账号',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO er_role_permission(role_id,permission_code)
SELECT id,'*' FROM er_role WHERE role_code='ADMIN';
INSERT INTO er_role_permission(role_id,permission_code)
SELECT id,p.permission_code FROM er_role r CROSS JOIN (VALUES ('RISK_VIEW'),('RISK_WRITE'),('MODEL_VIEW'),('ROBOT_VIEW')) p(permission_code) WHERE r.role_code='OPERATIONS';
INSERT INTO er_role_permission(role_id,permission_code)
SELECT id,'RISK_VIEW' FROM er_role WHERE role_code='VIEWER';
